### ISSUE TITLE
pgsql.* auto discovery not work

### ISSUE THREAD

**Issue by Vovanys** [sergiotocalini/zapgix#1]
Hello
you have a lot in the template pgsql.* (example key  pgsql.table.discovery[{$PG_CONNINFO}])
<img width="1431" alt="2018-07-18 13 39 29" src="https://user-images.githubusercontent.com/37010878/42879192-0b68f190-8a90-11e8-9f23-a5bb725c8436.png">
but in zabbix_agentd.conf.d there is no it.
Because of this, the auto discovery does not work for tables

**Comment by sergiotocalini** [comment]
Hello @Vovanys,
Indeed, this discovery rule is legacy, that is why it is disable by default.
I will add this in the following release.
Regards,
Sergio
