### ISSUE TITLE
Error in deploy_zabbix.sh

### ISSUE THREAD

**Issue by kuzakov** [sergiotocalini/zapgix#2]
Hi!
OS: Debian 9.5
ZBX: 3.4.12

In this script move 8 line from: cp ${SOURCE_DIR}/zapgix/zabbix_agentd.conf ${ZABBIX_DIR}/zabbix_agentd.d/zapgix.conf

To: cp ${SOURCE_DIR}/zapgix/zabbix_agentd.conf ${ZABBIX_DIR}/zabbix_agentd.conf.d/zapgix.conf

Thanks! It`s working!

**Comment by sergiotocalini** [comment]
Great!
