### ISSUE TITLE
Add zapgix to the PostgreSQL wiki?

### ISSUE THREAD

**Issue by justinclift** [sergiotocalini/zapgix#3]
Just stumbled across zapgix when looking for a way to monitor PG from Zabbix.

Zapgix doesn't seem to have an entry on the PG wiki:

&nbsp; &nbsp; https://wiki.postgresql.org/wiki/Monitoring#Zabbix

Do you reckon it should be there? :smile:

**Comment by sergiotocalini** [comment]
Hi Justin,
Thanks for your message.
Sure, it should be there. I am not sure who can update the wiki and add it. Please feel free to include if you are available to modify the wiki page.
Best,
Sergio
