### ISSUE TITLE
zapgix not working for monitoring posygresql 9.6

### ISSUE THREAD

**Issue by marfouk** [sergiotocalini/zapgix#5]
Hello,

I have follow alla steps installing zapgix for monitoring Postgresql 9.6 (zabbix server 4.0), no data for all items and in server log i have just this error : 
zapgix[connections-waiting]" became not supported: Value "
We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

sudo: no tty present and no askpass program specified
0" of type "string" is not suitable for value type "Numeric (unsigned)"

Any help please

**Comment by sergiotocalini** [comment]
Hello @marfouk 
It seems to be a sudo issue, please verify the zabbix user has access to use sudo on the postgresql server. I've just introduced a change on the sudoers file to ensure that for the user zabbix it won't require tty ;)

```
#~ cat /etc/sudoers.d/user_zabbix
# Allow the user zabbix to execute any command without password
Defaults:zabbix !requiretty
zabbix  ALL=(ALL:ALL) NOPASSWD:ALL
```

Best,
Sergio
